import type { IconType } from "react-icons";
import {
  SiHtml5,
  SiJavascript,
  SiTypescript,
  SiPhp,
  SiPython,
  SiMysql,
  SiReact,
  SiNextdotjs,
  SiTailwindcss,
  SiNodedotjs,
  SiExpress,
  SiGit,
  SiGithub,
  SiFigma,
  SiPostman,
  SiXampp,
  SiExpo,
  SiReactrouter,
  SiAxios,
  SiFramer,
  SiShadcnui,
  SiVercel,
  SiNpm,
  SiEslint,
  SiPrettier,
  SiJsonwebtokens,
  SiJson,
  SiPhpmyadmin,
  SiEclipseide,
  SiLinux,
  SiVite,
  SiThreedotjs,
  SiGreensock,
  SiWebgl,
  SiNumpy,
} from "react-icons/si";
import { DiCss3, DiAws } from "react-icons/di";
import {
  Database,
  Webhook,
  QrCode,
  RefreshCw,
  Smartphone,
  LayoutPanelLeft,
  Compass,
  PenTool,
  Accessibility,
  Workflow,
  KanbanSquare,
  ClipboardList,
  SearchCode,
  FlaskConical,
  FileText,
  ShieldCheck,
  CloudCog,
  KeyRound,
  Lock,
  ShieldAlert,
  GitBranch,
  Boxes,
  MoveVertical,
  Image as ImageIcon,
  Film,
  Palette,
  type LucideIcon,
} from "lucide-react";

export interface IconEntry {
  kind: "brand" | "concept" | "badge";
  Icon?: IconType | LucideIcon;
  color: string;
  badgeLabel?: string;
}

// Colors are each brand's real, documented mark color. Monochrome brand
// marks (Next.js, GitHub, Vercel, shadcn/ui, Express, Expo, JWT, JSON) use
// "currentColor" so they invert correctly between light/dark themes.
export const iconRegistry: Record<string, IconEntry> = {
  html5: { kind: "brand", Icon: SiHtml5, color: "#E34F26" },
  css3: { kind: "brand", Icon: DiCss3, color: "#1572B6" },
  javascript: { kind: "brand", Icon: SiJavascript, color: "#F7DF1E" },
  typescript: { kind: "brand", Icon: SiTypescript, color: "#3178C6" },
  php: { kind: "brand", Icon: SiPhp, color: "#777BB4" },
  python: { kind: "brand", Icon: SiPython, color: "#3776AB" },
  sql: { kind: "concept", Icon: Database, color: "#94A3B8" },
  mysql: { kind: "brand", Icon: SiMysql, color: "#4479A1" },
  react: { kind: "brand", Icon: SiReact, color: "#61DAFB" },
  reactNative: { kind: "brand", Icon: SiReact, color: "#61DAFB" },
  nextjs: { kind: "brand", Icon: SiNextdotjs, color: "currentColor" },
  tailwind: { kind: "brand", Icon: SiTailwindcss, color: "#06B6D4" },
  nodejs: { kind: "brand", Icon: SiNodedotjs, color: "#339933" },
  express: { kind: "brand", Icon: SiExpress, color: "currentColor" },
  git: { kind: "brand", Icon: SiGit, color: "#F05032" },
  github: { kind: "brand", Icon: SiGithub, color: "currentColor" },
  figma: { kind: "brand", Icon: SiFigma, color: "#F24E1E" },
  postman: { kind: "brand", Icon: SiPostman, color: "#FF6C37" },
  xampp: { kind: "brand", Icon: SiXampp, color: "#FB7A24" },
  expo: { kind: "brand", Icon: SiExpo, color: "currentColor" },
  reactRouter: { kind: "brand", Icon: SiReactrouter, color: "#CA4245" },
  axios: { kind: "brand", Icon: SiAxios, color: "#5A29E4" },
  framer: { kind: "brand", Icon: SiFramer, color: "#0055FF" },
  shadcn: { kind: "brand", Icon: SiShadcnui, color: "currentColor" },
  lucide: { kind: "concept", Icon: Boxes, color: "#F56565" },
  vercel: { kind: "brand", Icon: SiVercel, color: "currentColor" },
  npm: { kind: "brand", Icon: SiNpm, color: "#CB3837" },
  eslint: { kind: "brand", Icon: SiEslint, color: "#4B32C3" },
  prettier: { kind: "brand", Icon: SiPrettier, color: "#F7B93E" },
  jwt: { kind: "brand", Icon: SiJsonwebtokens, color: "currentColor" },
  json: { kind: "brand", Icon: SiJson, color: "currentColor" },
  phpmyadmin: { kind: "brand", Icon: SiPhpmyadmin, color: "#6C78AF" },
  eclipse: { kind: "brand", Icon: SiEclipseide, color: "#2C2255" },
  linux: { kind: "brand", Icon: SiLinux, color: "currentColor" },
  aws: { kind: "brand", Icon: DiAws, color: "#FF9900" },

  // Tooling used on the Kepler and Eclaire practice builds.
  vite: { kind: "brand", Icon: SiVite, color: "#646CFF" },
  threejs: { kind: "brand", Icon: SiThreedotjs, color: "currentColor" },
  r3f: { kind: "brand", Icon: SiThreedotjs, color: "#61DAFB" },
  gsap: { kind: "brand", Icon: SiGreensock, color: "#88CE02" },
  glsl: { kind: "brand", Icon: SiWebgl, color: "#990000" },
  numpy: { kind: "brand", Icon: SiNumpy, color: "#013243" },
  lenis: { kind: "concept", Icon: MoveVertical, color: "#94A3B8" },
  pillow: { kind: "concept", Icon: ImageIcon, color: "#94A3B8" },
  ffmpeg: { kind: "concept", Icon: Film, color: "#94A3B8" },
  cssModern: { kind: "concept", Icon: Palette, color: "#94A3B8" },

  restApi: { kind: "concept", Icon: Webhook, color: "#38BDF8" },
  qrCode: { kind: "concept", Icon: QrCode, color: "#A855F7" },
  crud: { kind: "concept", Icon: RefreshCw, color: "#22C55E" },
  responsive: { kind: "concept", Icon: Smartphone, color: "#38BDF8" },
  uiDesign: { kind: "concept", Icon: LayoutPanelLeft, color: "#A855F7" },
  uxDesign: { kind: "concept", Icon: Compass, color: "#A855F7" },
  wireframing: { kind: "concept", Icon: PenTool, color: "#A855F7" },
  accessibility: { kind: "concept", Icon: Accessibility, color: "#22C55E" },
  sdlc: { kind: "concept", Icon: Workflow, color: "#6366F1" },
  agile: { kind: "concept", Icon: KanbanSquare, color: "#6366F1" },
  requirements: { kind: "concept", Icon: ClipboardList, color: "#6366F1" },
  systemAnalysis: { kind: "concept", Icon: SearchCode, color: "#6366F1" },
  databaseDesign: { kind: "concept", Icon: Database, color: "#4479A1" },
  erd: { kind: "concept", Icon: GitBranch, color: "#4479A1" },
  testing: { kind: "concept", Icon: FlaskConical, color: "#F97316" },
  documentation: { kind: "concept", Icon: FileText, color: "#94A3B8" },
  networkSecurity: { kind: "concept", Icon: ShieldCheck, color: "#EF4444" },
  cloudSecurity: { kind: "concept", Icon: CloudCog, color: "#EF4444" },
  authentication: { kind: "concept", Icon: KeyRound, color: "#EF4444" },
  authorization: { kind: "concept", Icon: Lock, color: "#EF4444" },
  cybersecurity: { kind: "concept", Icon: ShieldAlert, color: "#EF4444" },

  vscode: { kind: "badge", color: "#007ACC", badgeLabel: "VS" },
  twilio: { kind: "badge", color: "#F22F46", badgeLabel: "TW" },
  ibmCloud: { kind: "badge", color: "#0F62FE", badgeLabel: "IBM" },
  emailjs: { kind: "badge", color: "#3B82F6", badgeLabel: "EJ" },
  nextThemes: { kind: "badge", color: "#8B5CF6", badgeLabel: "NT" },
};
